export const routeGroups = [
  { path: "/", component: "Home", requiresAuth: false },
  { path: "/home", component: "Home", requiresAuth: false },
  { path: "/login", component: "Login", requiresAuth: false },
  { path: "/my_account", component: "Dashboard", requiresAuth: true },
  { path: "/register", component: "Register", requiresAuth: false },
  { path: "/category", component: "Category", requiresAuth: true },
  { path: "/product", component: "Product", requiresAuth: true },
  { path: '/marketdata', component: 'MarketData', requiresAuth: true },
  { path: '/product/list', component: 'ProductListPage', requiresAuth: true },
  { path: '/orders/list', component: 'OrderList', requiresAuth: true },
  { path: '/trades/list', component: 'TradeList', requiresAuth: true },
  { path: '/trades/settle', component: 'SettleTrades' },
  { path: '/wallet', component: 'Wallet', requiresAuth: true },
  { path: '/report', component: 'UserReports', requiresAuth: true },
];
